# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_remyrust_wrappers", use_symbols = TRUE, package_name = "remyrust")

#' @usage NULL
#' @useDynLib remyrust, .registration = TRUE
NULL

r_entry <- function(par_input, ngen, max_time, obs, iter) .Call(wrap__r_entry, par_input, ngen, max_time, obs, iter)


# nolint end
